"""
Django settings for djangoworkshop project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import dj_database_url
import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)lltjn-t6lu$z^llf!=#a!+jaso_k$&x^$^3g0r#cig1f*g-zg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','husnashop.onrender.com']

STATIC_URL='/static/'
STATIC_ROOT=os.path.join(BASE_DIR,'static')

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'staic','media')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap4',
    'stripe'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoworkshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.menu_links',
                'store.context_processors.counter'
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoworkshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databasepos
if not DEBUG:
    DATABASES = {
        'default':dj_database_url.parse(os.environ.get('postgres://db_2204_user:vNiNovmg7JeYiNx7RSDitpvazfIINeS6@dpg-co33eqol5elc73d6s9m0-a.singapore-postgres.render.com/db_2204'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'storedb',
            'USER' : 'root',
            'PASSWORD' : 'Husna26531',
            'HOST' : 'localhost',
            'PORT' : ''
        }
    }

# postgres://db_2204_user:vNiNovmg7JeYiNx7RSDitpvazfIINeS6@dpg-co33eqol5elc73d6s9m0-a/db_2204

# DATABASES=["default"]=dj_database_url.parse("postgres://db_2204_user:vNiNovmg7JeYiNx7RSDitpvazfIINeS6@dpg-co33eqol5elc73d6s9m0-a/db_2204")
# postgres://db_2204_user:vNiNovmg7JeYiNx7RSDitpvazfIINeS6@dpg-co33eqol5elc73d6s9m0-a.singapore-postgres.render.com/db_2204




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'

PUBLIC_KEY='pk_test_51OyfqUP0Ow5V3YnpX7txyl2iDnFgORv2zGKd4LF0ZiC0JtavPoSmstYNl6zrktyrZ9zgCULOQrUU2q2o1SgCDBL500d6XbkbkA'
SECRET_KEY='sk_test_51OyfqUP0Ow5V3YnpGCEPY20zYJWK3KvUFNpCzlFTffEZKgneZ8xAeE9sjRVTlrvBWJqdUL1LPrLGYWL2Md4ai9rd00lrRuziaO'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
